name: Build and Release SWS Modern

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-macos:
    name: Build macOS
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install cmake php

      - name: Apply WDL/zlib patch for Xcode compatibility
        run: |
          # Patch já aplicado no repositório
          echo "WDL/zlib patch already applied"

      - name: Configure CMake
        run: |
          cmake -S . -B build \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"

      - name: Build
        run: |
          cmake --build build --config Release -j$(sysctl -n hw.ncpu)

      - name: Package
        run: |
          cd build
          cpack -G DragNDrop

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sws-modern-macos
          path: build/*.dmg

  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"

      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Package
        run: |
          cd build
          cpack -G NSIS -C Release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sws-modern-windows
          path: build/*.exe

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            php-cli \
            libgtk-3-dev \
            libgdk-pixbuf2.0-dev

      - name: Configure CMake
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: |
          cmake --build build --config Release -j$(nproc)

      - name: Package
        run: |
          cd build
          cpack -G TXZ

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sws-modern-linux
          path: build/*.tar.xz

  create-release:
    name: Create Release
    needs: [build-macos, build-windows, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            sws-modern-macos/*.dmg
            sws-modern-windows/*.exe
            sws-modern-linux/*.tar.xz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
